### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by svua** [Altinity/clickhouse-backup#227]
Hello All,
I'm trying to restore a backup

```
bash-5.0# clickhouse-backup -v
Version:         1.0.11
Git Commit:      2317763aa59c2e7cb0f7efd96f1c339998d2427e
Build Date:      2021-05-27
```

```
bash-5.0# clickhouse-backup list |grep 2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local
2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local   227.01GiB   21/07/2021 23:27:39   remote      zstd
```

```
bash-5.0# clickhouse-backup restore_remote 2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local
2021/07/22 09:44:23  info done                      backup=2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local operation=download table=backup.installs_local
 0 B / 151.68 GiB [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe97298]

goroutine 1 [running]:
github.com/mholt/archiver/v3.(*TarZstd).wrapReader(0xc000144d58)
        /home/runner/go/pkg/mod/github.com/mholt/archiver/v3@v3.5.0/tarzst.go:89 +0x78
github.com/mholt/archiver/v3.(*TarZstd).Open(0xc000144d58, 0x14c7d20, 0xc0003bbba8, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/mholt/archiver/v3@v3.5.0/tarzst.go:63 +0x2b
github.com/AlexAkulov/clickhouse-backup/pkg/new_storage.(*BackupDestination).CompressedStreamDownload(0xc000527840, 0xc0003dfd80, 0x78, 0xc0003a95f0, 0x88, 0x0, 0x0)
        /home/runner/work/clickhouse-backup/clickhouse-backup/pkg/new_storage/general.go:162 +0x3a8
github.com/AlexAkulov/clickhouse-backup/pkg/backup.(*Backuper).downloadTableData(0xc000329120, 0xc0001605a0, 0x48, 0xc0005f5320, 0xc0003fdc08, 0x6, 0x20e17549, 0xed88aa46b, 0x0, 0x0, ...)
        /home/runner/work/clickhouse-backup/clickhouse-backup/pkg/backup/download.go:188 +0x505
github.com/AlexAkulov/clickhouse-backup/pkg/backup.(*Backuper).Download(0xc000329120, 0x7ffc7c1a8374, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/clickhouse-backup/clickhouse-backup/pkg/backup/download.go:159 +0xe58
github.com/AlexAkulov/clickhouse-backup/pkg/backup.(*Backuper).RestoreFromRemote(0xc000329120, 0x7ffc7c1a8374, 0x48, 0x0, 0x0, 0x1000000, 0x14d9200, 0x1c24460)
        /home/runner/work/clickhouse-backup/clickhouse-backup/pkg/backup/restore_remote.go:4 +0x65
main.main.func10(0xc00044c2c0, 0xc000040700, 0xc00057e870)
        /home/runner/work/clickhouse-backup/clickhouse-backup/cmd/clickhouse-backup/main.go:216 +0x1f6
github.com/urfave/cli.HandleAction(0x10d25a0, 0x130b340, 0xc00044c2c0, 0xc00044c2c0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:523 +0x105
github.com/urfave/cli.Command.Run(0x12c54ac, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12cb854, 0x14, 0x12fd221, ...)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:174 +0x579
github.com/urfave/cli.(*App).Run(0xc0004ff180, 0xc00018c000, 0x3, 0x3, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:276 +0x7e8
main.main()
        /home/runner/work/clickhouse-backup/clickhouse-backup/cmd/clickhouse-backup/main.go:280 +0x15de
```

```
bash-5.0# clickhouse-backup list |grep 2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local
2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local   ???         22/07/2021 09:44:23   local       old-format
2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local   227.01GiB   21/07/2021 23:27:39   remote      zstd
```

How can I check the restore of a backup? The recommendation in all tutorials to delete a table or database looks very funny.
It would be nice to be able to restore the table to the test database.

**Comment by AlexAkulov** [comment]
Hi @svua!

Version 1.0.11? Do you use Altinity fork?
Judging by build date your version corresponds to v1.0.0-beta2. The similar issue was fixed later in v1.0.0.
Try to use latest version of clickhouse-backup.

**Comment by Slach** [comment]
@svua
could you run
```
clickhouse-backup delete local 2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local
clickhouse-backup download 2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local
clickhouse-backup restore 2021-07-21_23_26_46.chi-cold-storage-2-cluster-1-0.backup.installs_local
```
?

do you have enough free space on your `/var/lib/clickhouse/backup`?
could you share `df -h /var/lib/clickhouse/backup` ?

**Comment by Slach** [comment]
also, could you check the latest official release https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0?

**Comment by svua** [comment]
I changed image from altinity/clickhouse-backup:1.0.11 to alexakulov/clickhouse-backup:1.0.0. And restored the backup.

**Comment by Slach** [comment]
could you also try `altinity/clickhouse-backup:1.0.14`?
