### ISSUE TITLE
Build from source using make: error

### ISSUE THREAD

**Issue by DonJuanMatus** [Altinity/clickhouse-backup#492]
Hi! 

I've tried to build clickhouse-backup from the latest source using `make` and got an error

```
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/usr/local/lib/node_modules/fpm/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/fpm/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/fpm/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Node.js v18.6.0
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/usr/local/lib/node_modules/fpm/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/fpm/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/fpm/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Node.js v18.6.0
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/usr/local/lib/node_modules/fpm/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/fpm/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/fpm/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Node.js v18.6.0
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/usr/local/lib/node_modules/fpm/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/fpm/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/fpm/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Node.js v18.6.0
```

Environment:
alpine 3.16.2
go1.18.5
Node.js v18.6

Nonetheless, binary file has been compiled using `make` with -i option  and it seems to work correctly. It can process backup/restore operations. 

Is there any system requirements list ?
Could you please provide some instructions on building using `make` ?

**Comment by Slach** [comment]
sorry, which kind of `make` do you use?
`clickhouse-backup` written with `golang` and doesn't use any `nodejs` related tools

**Comment by Slach** [comment]
ahh, i see
`fpm` it's a ruby application to make deb and rpm packages, not `nodejs`

try 
`gem install fpm`

**Comment by DonJuanMatus** [comment]
> gem install fpm

Thanks, it worked fine.
