### ISSUE TITLE
--partitions= parameter get panic

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#544]
```
panic: runtime error: slice bounds out of range [192:191]
goroutine 1 [running]:
[github.com/AlexAkulov/clickhouse-backup/pkg/backup.filterPartsByPartitionsFilter({0x0](http://github.com/AlexAkulov/clickhouse-backup/pkg/backup.filterPartsByPartitionsFilter(%7B0x0), {0xc00092b6e0, 0xf}, {0xc00092b6d8, 0x3}, {0x0, 0x0}, 0xc0003ec810, {0xc000208300, 0x2e1}, ...}, ...)
        /home/runner/work/clickhouse-backup/clickhouse-backup/pkg/backup/table_pattern.go:117 +0x33e
[github.com/AlexAkulov/clickhouse-backup/pkg/backup.getTableListByPatternLocal.func1({0xc000486c00](http://github.com/AlexAkulov/clickhouse-backup/pkg/backup.getTableListByPatternLocal.func1(%7B0xc000486c00), 0x57}, {0x16423c8, 0xc0004880d0}, {0x0?, 0x0?})
        /home/runner/work/clickhouse-backup/clickhouse-backup/pkg/backup/table_pattern.go:100 +0x949
path/filepath.walk({0xc000486c00, 0x57}, {0x16423c8, 0xc0004880d0}, 0xc00020fd78)
        /opt/hostedtoolcache/go/1.18.3/x64/src/path/filepath/path.go:430 +0x123
path/filepath.walk({0xc00041c4b0, 0x42}, {0x16423c8, 0xc000465040}, 0xc00020fd78)
        /opt/hostedtoolcache/go/1.18.3/x64/src/path/filepath/path.go:454 +0x285
path/filepath.walk({0xc0003a0e00, 0x3e}, {0x16423c8, 0xc0000e1860}, 0xc00020fd78)
        /opt/hostedtoolcache/go/1.18.3/x64/src/path/filepath/path.go:454 +0x285
path/filepath.Walk({0xc0003a0e00, 0x3e}, 0xc00020fd78)
```

**Comment by den-crane** [comment]
Also it would be nice to have some examples how to use `--partitions=` it's unclear now how to pass several partitions
`--partitions=2020101,2020102` what character to use as a separator `,` ?

Is it possible to use regular expressions? `--partitions=2020*`?

**Comment by Slach** [comment]
no, regexp and wildcard for partition filterting is not available
and yes, for multiple partitions use comma as separator

**Comment by Slach** [comment]
fixed https://github.com/AlexAkulov/clickhouse-backup/pull/546
